[package]
name = "snip20-reference-impl"
version = "1.0.0"
authors = ["Itzik <itzik@keytango.io>"]
edition = "2021"
exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
#default = ["debug-print"]
backtraces = ["cosmwasm-std/backtraces"]
library = []

# debug-print = ["cosmwasm-std/debug-print"]
[dependencies]
shade-toolkit = { path = "../plus/packages/toolkit", defaut-features = false }
cosmwasm-std = { package = "secret-cosmwasm-std", version = "1.1.10" }
cosmwasm-storage = { package = "secret-cosmwasm-storage", version = "1.1.10" }
rand = { version = "0.8.5", default-features = false }
secret-toolkit = { git = "https://github.com/hoomp3/secret-toolkit", features = [
  "permit",
  "viewing-key",
] }
secret-toolkit-crypto = { git = "https://github.com/hoomp3/secret-toolkit", features = [
  "rand",
  "hash",
] }

schemars = "0.8.12"
serde = { version = "1.0.158", default-features = false, features = ["derive"] }
base64 = "0.21.0"

[dev-dependencies]
cosmwasm-schema = { version = "1.1.8" }
